name: deploy 

on:
  workflow_run:
    workflows: ["build"]
    types:
      - "completed"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 'depoy to docker host via ssh'
        run: |
          docker container stop word-guess
          docker container rm word-guess
          docker image rm word-guess:latest
          docker run -d --name word-guess -p 3210:3000 anthonymolinari/word-guess:latest
